### ISSUE TITLE
Development of Neuron class

### ISSUE THREAD

**Issue by drkostas** [drkostas/COSC525-Project1#1]

**Comment by GCantral** [comment]
Let me know if there are any changes you want, and if not ill close the issue.

**Comment by drkostas** [comment]
Everything looks good! Just one note,  I put `*args, **kwargs` as the args of the init function as a placeholder. Feel free to replace them with the actual arguments if you want, or if you want to leave it like this it's still ok!

**Comment by GCantral** [comment]
Ok sounds good! I wasnt sure if that was just how you preferred it to be formatted. I may change it later if we make the other classes have actual arguments

**Comment by drkostas** [comment]
Hi @GCantral, I changed the arguments in Neuron class and did some automatic formatting, feel free to change them as you wish. I have one question, [on line 13](https://github.com/drkostas/COSC525-Project1/blob/master/src/neuron.py#L13) why are you doing ` - .5 * 2` on the random values? I'm asking because I may have to do the same in my code accordingly too.
